"""
Format and save keyword research findings to .tmp/keyword_report_YYYY-MM-DD.md.
Called after using Ahrefs MCP tools to gather data.

Usage:
  python tools/keyword_report.py --input data.json
  python tools/keyword_report.py  # reads from stdin (pipe Ahrefs output)

Input JSON format (list of keyword objects):
[
  {
    "keyword": "mobile phlebotomy atlanta",
    "volume": 320,
    "kd": 18,
    "intent": "transactional",
    "our_rank": null,
    "competitor_rank": 3,
    "action": "new page"
  },
  ...
]
"""
import os, sys, json, argparse
from datetime import date


def format_report(keywords):
    today = date.today().isoformat()
    lines = [
        f"# Keyword Research Report — {today}",
        f"**Site:** fastrakmobilelab.com",
        f"**Generated by:** keyword_report.py",
        "",
        "## Opportunity Summary",
        "",
        f"| Keyword | Vol/mo | KD | Intent | Our Rank | Comp Rank | Action |",
        f"|---------|--------|----|--------|----------|-----------|--------|",
    ]

    quick_wins, new_pages, gaps = [], [], []

    for kw in keywords:
        keyword = kw.get("keyword", "")
        volume = kw.get("volume", 0)
        kd = kw.get("kd", "?")
        intent = kw.get("intent", "?")
        our_rank = kw.get("our_rank") or "—"
        comp_rank = kw.get("competitor_rank") or "—"
        action = kw.get("action", "?")

        lines.append(f"| {keyword} | {volume} | {kd} | {intent} | {our_rank} | {comp_rank} | {action} |")

        if action == "optimize existing":
            quick_wins.append(keyword)
        elif action == "new page":
            new_pages.append(keyword)
        elif action == "close gap":
            gaps.append(keyword)

    lines += [
        "",
        "## Prioritized Actions",
        "",
        "### Quick Wins (optimize existing pages)",
    ]
    lines += [f"- {k}" for k in quick_wins] or ["- None identified"]

    lines += ["", "### New Pages to Create"]
    lines += [f"- {k}" for k in new_pages] or ["- None identified"]

    lines += ["", "### Competitor Gap Keywords"]
    lines += [f"- {k}" for k in gaps] or ["- None identified"]

    lines += [
        "",
        "## Next Step",
        "Feed top opportunities into `workflows/seo_content_creation.md`.",
    ]

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", help="Path to JSON file with keyword data")
    parser.add_argument("--output", help="Output path (default: .tmp/keyword_report_YYYY-MM-DD.md)")
    args = parser.parse_args()

    if args.input:
        with open(args.input) as f:
            keywords = json.load(f)
    else:
        print("Reading from stdin... (paste JSON, then Ctrl+Z on Windows)", file=sys.stderr)
        keywords = json.load(sys.stdin)

    report = format_report(keywords)

    output_path = args.output or f".tmp/keyword_report_{date.today().isoformat()}.md"
    os.makedirs(os.path.dirname(output_path), exist_ok=True) if os.path.dirname(output_path) else None
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"Report saved: {output_path}")


if __name__ == "__main__":
    main()
